FROM python:3.11-slim-bookworm

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc python3-dev libpq-dev && \
    rm -rf /var/lib/apt/lists/*

# Копируем файлы зависимостей в корень рабочей директории контейнера
COPY requirements.txt .
COPY tests/requirements-test.txt requirements-test.txt

# Устанавливаем зависимости из файлов, лежащих в текущей директории (/app)
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt -r requirements-test.txt

# Копируем весь исходный код проекта
COPY . .

EXPOSE 5000
CMD ["gunicorn", "app.main:app", "--workers", "2", "--bind", "0.0.0.0:5000"]