version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: papaya_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: papaya_web
    command: gunicorn --bind 0.0.0.0:5000 main:app
    ports:
      - "5000:5000"
    environment:
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db  # Важно: имя сервиса базы данных в docker-compose
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - INIT_EVENT_ID = 111
      - INIT_EVENT_NAME = my_event
      - INIT_EVENT_PLACE = my_place
      - INIT_EVENT_MIN_GRADE = 1
      - INIT_EVENT_MAX_GRADE = 11
      - INIT_EVENT_MIN_AGE = 6
      - INIT_EVENT_MAX_AGE = 17
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  pgdata: