services:
  - type: web
    name: papaya
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: postgresql://postgres:JeJB$HXr%XFs2@db.xbiauujzrxoduwgfnzhr.supabase.co:5432/postgres
          property: url
s
databases:
  - name: papaya-db
    databaseName: papaya
    user: papaya
    plan: free