services:
  - type: web
    name: papaya
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: DB_URL
        fromDatabase:
          name: papaya-db
          property: connectionString
      - key: INIT_EVENT_ID
        value: "111"
      - key: INIT_EVENT_NAME
        value: "Мероприятие от Papaya"
      - key: INIT_EVENT_PLACE
        value: "Онлайн"
      - key: INIT_EVENT_MIN_GRADE
        value: "1"
      - key: INIT_EVENT_MAX_GRADE
        value: "11"
      - key: INIT_EVENT_MIN_AGE
        value: "6"
      - key: INIT_EVENT_MAX_AGE
        value: "17"
databases:
  - name: papaya-db
    databaseName: papaya
    user: papaya
    plan: free